version: "3.8"

services:
  users1:
    build: ./users
    container_name: users1
    expose:
      - "3000"
    networks:
      - my_network
    environment:
      - NODE_ENV=development

  users2:
    build: ./users
    container_name: users2
    expose:
      - "3000"
    networks:
      - my_network
    volumes:
      - ./users:/app
    environment:
      - NODE_ENV=development

  load-balancer:
    build: ./nginx-loadbalancer
    container_name: load-balancer
    expose:
      - "80"
    depends_on:
      - users1
      - users2
    networks:
      - my_network
    volumes:
      - ./nginx-loadbalancer:/etc/nginx

  api-gateway:
    build: ./nginx-api-gateway
    container_name: api-gateway
    ports:
      - "5000:80"
    expose:
      - "5000"
    depends_on:
      - load-balancer
    networks:
      - my_network
    volumes:
      - ./nginx-api-gateway:/etc/nginx

networks:
  my_network:
    driver: bridge
